version: '3.8'
services:
  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data

  pg-backup:
    build: .
    environment:
      PG_URLS: "prefix1=postgres://postgres:postgres@postgres:5432/postgres"
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "minioadmin"
      S3_SECRET_KEY: "minioadmin"
      S3_BUCKET: "backups"
    depends_on:
      - minio
    networks:
      - backup-net

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backup-net

volumes:
  minio-data:

networks:
  backup-net:
